#!/usr/bin/env bash

# Shared lifecycle for the full HTTP completion, steady-state, and staircase contracts.

http_matched_extract_last_json_object() {
  local source_log="$1"
  local target_json="$2"
  local temp_json="${target_json}.tmp.$$"

  if ! awk '
    /^\{/ {
      in_json = 1
      buffer = $0 ORS
      next
    }
    in_json {
      buffer = buffer $0 ORS
      if ($0 ~ /^\}/) {
        last = buffer
        in_json = 0
        buffer = ""
      }
    }
    END {
      if (last == "") {
        exit 1
      }
      printf "%s", last
    }
  ' "${source_log}" > "${temp_json}"; then
    rm -f "${temp_json}"
    return 1
  fi
  if ! jq -e . "${temp_json}" >/dev/null; then
    rm -f "${temp_json}"
    return 1
  fi
  mv "${temp_json}" "${target_json}"
}

http_matched_persist_result() {
  if http_matched_extract_last_json_object "${RUN_REPORT_LOG}" "${RUN_REPORT_JSON}"; then
    echo "[INFO] persisted result JSON=${RUN_REPORT_JSON}"
  else
    echo "[WARN] could not extract result JSON from ${RUN_REPORT_LOG}" >&2
    rm -f "${RUN_REPORT_JSON}"
  fi
}

http_matched_validate_common() {
  BENCHMARK_RUNTIME_PROFILE="${BENCHMARK_RUNTIME_PROFILE:-core-capacity}"
  if [[ "${MARKET_ID}" != "ENERGY-SPOT" ]]; then
    echo "[ERROR] Order HTTP currently assigns market ENERGY-SPOT; MARKET_ID must match." >&2
    return 2
  fi
  case "${DIAGNOSTICS_LEVEL}" in
    none|baseline|light|deep)
      ;;
    *)
      echo "[ERROR] unsupported DIAGNOSTICS_LEVEL=${DIAGNOSTICS_LEVEL}" >&2
      return 2
      ;;
  esac
  case "${BENCHMARK_RUNTIME_PROFILE}" in
    core-capacity|production-equivalent|custom)
      ;;
    *)
      echo "[ERROR] unsupported BENCHMARK_RUNTIME_PROFILE=${BENCHMARK_RUNTIME_PROFILE}" >&2
      return 2
      ;;
  esac
}

http_matched_configure_runtime_profile() {
  BENCHMARK_RUNTIME_PROFILE="${BENCHMARK_RUNTIME_PROFILE:-core-capacity}"
  export BENCHMARK_RUNTIME_PROFILE
  case "${BENCHMARK_RUNTIME_PROFILE}" in
    core-capacity)
      export EAP_RATE_LIMIT_ENABLED="${EAP_RATE_LIMIT_ENABLED:-false}"
      export EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED="${EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED:-false}"
      export EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED="${EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED:-false}"
      export EAP_MATCH_RESERVATION_RECONCILER_ENABLED="${EAP_MATCH_RESERVATION_RECONCILER_ENABLED:-false}"
      ;;
    production-equivalent)
      export EAP_RATE_LIMIT_ENABLED="${EAP_RATE_LIMIT_ENABLED:-true}"
      export EAP_ORDER_COMMAND_POOL_SIZE=10
      export EAP_ORDER_COMMAND_POOL_MIN_IDLE=2
      export EAP_ORDER_CONSUMER_POOL_SIZE=15
      export EAP_ORDER_CONSUMER_POOL_MIN_IDLE=4
      export EAP_ORDER_PROJECTION_POOL_SIZE=5
      export EAP_ORDER_PROJECTION_POOL_MIN_IDLE=1
      export EAP_ORDER_REALTIME_UPDATES_ENABLED=true
      export EAP_ORDER_ASSET_RESERVATION_CONFIRMED_CONCURRENCY=8
      export EAP_ORDER_ASSET_RESERVATION_CONFIRMED_BATCH_SIZE=1
      export EAP_ORDER_ASSET_RESERVATION_CONFIRMED_RECEIVE_TIMEOUT_MS=50
      export EAP_ORDER_ASSET_RESERVATION_CONFIRMED_SINGLE_ROUND_TRIP_ENABLED=false
      export EAP_ORDER_ASSET_RESERVATION_FAILED_CONCURRENCY=4
      export EAP_ORDER_MATCHED_CONCURRENCY=4
      export EAP_ORDER_TRADE_EXECUTED_CONCURRENCY=4
      export EAP_ORDER_TRADE_EXECUTED_BATCH_SIZE=1
      export EAP_ORDER_TRADE_EXECUTED_RECEIVE_TIMEOUT_MS=50
      export EAP_ORDER_OUTBOX_BATCH_SIZE=200
      export EAP_ORDER_OUTBOX_PUBLISH_CONCURRENCY=1
      export EAP_ORDER_OUTBOX_BATCH_CONFIRM_ENABLED=false
      export EAP_ORDER_OUTBOX_ASYNC_RELAY_ENABLED=false
      export EAP_ORDER_OUTBOX_POLL_INTERVAL_MS=500
      export EAP_ORDER_PROJECTION_POLL_INTERVAL_MS=100
      export EAP_ORDER_PROJECTION_REPAIR_ENABLED=true

      export EAP_WALLET_DB_POOL_SIZE="${EAP_WALLET_DB_POOL_SIZE:-10}"
      export EAP_WALLET_DB_POOL_MIN_IDLE="${EAP_WALLET_DB_POOL_MIN_IDLE:-10}"
      export EAP_WALLET_RABBIT_CONCURRENCY=1
      export EAP_WALLET_RABBIT_MAX_CONCURRENCY=8
      export EAP_WALLET_RABBIT_PREFETCH=10
      export EAP_WALLET_ORDER_SUBMITTED_CONCURRENCY=8
      export EAP_WALLET_TRADE_EXECUTED_CONCURRENCY="${EAP_WALLET_TRADE_EXECUTED_CONCURRENCY:-4}"
      export EAP_WALLET_OUTBOX_BATCH_SIZE=200
      export EAP_WALLET_OUTBOX_PUBLISH_CONCURRENCY=1
      export EAP_WALLET_OUTBOX_BATCH_CONFIRM_ENABLED=false
      export EAP_WALLET_OUTBOX_ASYNC_RELAY_ENABLED=false
      export EAP_WALLET_OUTBOX_POLL_INTERVAL_MS=500

      export EAP_MATCH_DB_POOL_SIZE=10
      export EAP_MATCH_DB_POOL_MIN_IDLE=10
      export EAP_MATCH_RABBIT_CONCURRENCY=1
      export EAP_MATCH_RABBIT_MAX_CONCURRENCY=8
      export EAP_MATCH_RABBIT_PREFETCH=10
      export EAP_MATCH_ORDER_CONFIRMED_CONCURRENCY=8
      export EAP_MATCH_ORDER_TRADE_APPLIED_CONCURRENCY=2
      export EAP_MATCH_WALLET_TRADE_SETTLED_CONCURRENCY=2
      export EAP_MATCH_COMPLETION_MARKER_BATCH_SIZE=1
      export EAP_MATCH_COMPLETION_MARKER_RECEIVE_TIMEOUT_MS=50
      export EAP_MATCH_TRADE_OUTBOX_BATCH_SIZE=200
      export EAP_MATCH_TRADE_OUTBOX_PUBLISH_CONCURRENCY=1
      export EAP_MATCH_TRADE_OUTBOX_BATCH_CONFIRM_ENABLED=false
      export EAP_MATCH_TRADE_OUTBOX_POLL_INTERVAL_MS=500
      export EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED=true
      export EAP_MATCH_USER_OPEN_ORDER_INDEX_ENABLED=true
      export EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED=true
      export EAP_MATCH_TRADE_COMPLETION_RECONCILER_BATCH_SIZE=100
      export EAP_MATCH_TRADE_COMPLETION_RECONCILER_POLL_INTERVAL_MS=5000
      export EAP_MATCH_RESERVATION_RECONCILER_ENABLED=true
      export EAP_MATCH_RESERVATION_RECONCILER_BATCH_SIZE=100
      export EAP_MATCH_RESERVATION_RECONCILER_POLL_INTERVAL_MS=5000
      export EAP_MATCH_RESERVATION_CLEANUP_BATCH_SIZE=500
      export EAP_MATCH_RESERVATION_CLEANUP_POLL_INTERVAL_MS=100
      export EAP_MATCH_RESERVATION_CLEANUP_INITIAL_BACKOFF_MS=1000
      export EAP_MATCH_RESERVATION_CLEANUP_MAX_BACKOFF_MS=300000
      export EAP_MATCH_RESERVATION_CLEANUP_PROCESSING_TIMEOUT_SECONDS=30
      ;;
    custom)
      ;;
  esac
  echo "[INFO] benchmarkRuntimeProfile=${BENCHMARK_RUNTIME_PROFILE}"
}

http_matched_assert_environment() {
  if [[ "${ASSERT_LOADTEST_ENVIRONMENT}" != "true" ]]; then
    return 0
  fi
  RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" \
    REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
    bash "${ROOT_DIR}/scripts/load-test/assert-loadtest-environment.sh"
}

http_matched_start_diagnostics() {
  if [[ "${DIAGNOSTICS_LEVEL}" == "none" || "${DIAGNOSTICS_LEVEL}" == "baseline" ]]; then
    return 0
  fi
  mkdir -p "${RUN_DIAG_DIR}"
  if [[ "${DIAGNOSTICS_LEVEL}" == "deep" ]]; then
    DIAG_DIR="${RUN_DIAG_DIR}" \
      MARKET_ID="${MARKET_ID}" \
      DIAGNOSTICS_LEVEL="${DIAGNOSTICS_LEVEL}" \
      RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" \
      REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
      bash "${ROOT_DIR}/scripts/load-test/collect-loadtest-diagnostics.sh" reset
  fi
  rm -f "${RUN_DIAG_DIR}/sampler.stop" 2>/dev/null || true
  DIAG_DIR="${RUN_DIAG_DIR}" \
    MARKET_ID="${MARKET_ID}" \
    DIAGNOSTICS_LEVEL="${DIAGNOSTICS_LEVEL}" \
    DIAGNOSTIC_SAMPLE_INTERVAL_SECONDS="${DIAGNOSTIC_SAMPLE_INTERVAL_SECONDS}" \
    RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" \
    REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
    bash "${ROOT_DIR}/scripts/load-test/collect-loadtest-diagnostics.sh" sample &
  DIAG_SAMPLER_PID="$!"
  echo "[INFO] diagnostics sampler pid=${DIAG_SAMPLER_PID}, dir=${RUN_DIAG_DIR}"
}

http_matched_stop_diagnostics() {
  if [[ -z "${DIAG_SAMPLER_PID:-}" ]]; then
    return 0
  fi
  DIAG_DIR="${RUN_DIAG_DIR}" \
    RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" \
    REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
    bash "${ROOT_DIR}/scripts/load-test/collect-loadtest-diagnostics.sh" stop-sample >/dev/null 2>&1 || true
  wait "${DIAG_SAMPLER_PID}" >/dev/null 2>&1 || true
  DIAG_SAMPLER_PID=""
}

http_matched_collect_after_run_diagnostics() {
  case "${DIAGNOSTICS_LEVEL}" in
    light)
      DIAG_DIR="${RUN_DIAG_DIR}" MARKET_ID="${MARKET_ID}" DIAGNOSTICS_LEVEL="${DIAGNOSTICS_LEVEL}" \
        RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
        bash "${ROOT_DIR}/scripts/load-test/collect-loadtest-diagnostics.sh" after-run-light || true
      ;;
    deep)
      DIAG_DIR="${RUN_DIAG_DIR}" MARKET_ID="${MARKET_ID}" DIAGNOSTICS_LEVEL="${DIAGNOSTICS_LEVEL}" \
        RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" REDIS_CONTAINER="${LOADTEST_REDIS_CONTAINER}" \
        bash "${ROOT_DIR}/scripts/load-test/collect-loadtest-diagnostics.sh" after-run || true
      ;;
  esac
  if [[ -f "${RUN_DIAG_DIR}/runtime-samples.log" ]]; then
    local hot_window_summary
    if hot_window_summary="$(bash "${ROOT_DIR}/scripts/load-test/summarize-runtime-hot-window.sh" "${RUN_DIAG_DIR}")"; then
      echo "[INFO] runtime hot-window summary=${hot_window_summary}"
    else
      echo "[WARN] could not summarize runtime hot window" >&2
    fi
  fi
}

http_matched_start_services() {
  if [[ "${START_SERVICES}" != "true" ]]; then
    return 0
  fi
  echo "[INFO] stopping stale loadtest services"
  bash "${ROOT_DIR}/scripts/load-test/stop-loadtest-services.sh"
  echo "[INFO] purging EAP queues before service start"
  RABBIT_CONTAINER="${LOADTEST_RABBIT_CONTAINER}" \
    bash "${ROOT_DIR}/scripts/load-test/purge-eap-queues.sh"
  http_matched_pre_reset_data

    EAP_MATCH_DB_POOL_SIZE="${EAP_MATCH_DB_POOL_SIZE:-35}" \
    EAP_MATCH_DB_POOL_MIN_IDLE="${EAP_MATCH_DB_POOL_MIN_IDLE:-10}" \
    EAP_MATCH_RABBIT_CONCURRENCY="${EAP_MATCH_RABBIT_CONCURRENCY:-8}" \
    EAP_MATCH_RABBIT_MAX_CONCURRENCY="${EAP_MATCH_RABBIT_MAX_CONCURRENCY:-32}" \
    EAP_MATCH_RABBIT_PREFETCH="${EAP_MATCH_RABBIT_PREFETCH:-50}" \
    EAP_MATCH_USER_OPEN_ORDER_INDEX_ENABLED="${EAP_MATCH_USER_OPEN_ORDER_INDEX_ENABLED:-false}" \
    EAP_MATCH_ORDER_CONFIRMED_CONCURRENCY="${EAP_MATCH_ORDER_CONFIRMED_CONCURRENCY:-12}" \
    EAP_MATCH_ORDER_TRADE_APPLIED_CONCURRENCY="${EAP_MATCH_ORDER_TRADE_APPLIED_CONCURRENCY:-12}" \
    EAP_MATCH_WALLET_TRADE_SETTLED_CONCURRENCY="${EAP_MATCH_WALLET_TRADE_SETTLED_CONCURRENCY:-6}" \
    EAP_MATCH_COMPLETION_MARKER_BATCH_SIZE="${EAP_MATCH_COMPLETION_MARKER_BATCH_SIZE:-50}" \
    EAP_MATCH_COMPLETION_MARKER_RECEIVE_TIMEOUT_MS="${EAP_MATCH_COMPLETION_MARKER_RECEIVE_TIMEOUT_MS:-25}" \
    EAP_MATCH_TRADE_OUTBOX_BATCH_SIZE="${EAP_MATCH_TRADE_OUTBOX_BATCH_SIZE:-500}" \
    EAP_MATCH_TRADE_OUTBOX_PUBLISH_CONCURRENCY="${EAP_MATCH_TRADE_OUTBOX_PUBLISH_CONCURRENCY:-4}" \
    EAP_MATCH_TRADE_OUTBOX_BATCH_CONFIRM_ENABLED="${EAP_MATCH_TRADE_OUTBOX_BATCH_CONFIRM_ENABLED:-false}" \
    EAP_MATCH_TRADE_OUTBOX_POLL_INTERVAL_MS="${EAP_MATCH_TRADE_OUTBOX_POLL_INTERVAL_MS:-100}" \
    EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED="${EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED:-false}" \
    EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED="${EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED:-false}" \
    EAP_MATCH_TRADE_COMPLETION_RECONCILER_BATCH_SIZE="${EAP_MATCH_TRADE_COMPLETION_RECONCILER_BATCH_SIZE:-500}" \
    EAP_MATCH_TRADE_COMPLETION_RECONCILER_POLL_INTERVAL_MS="${EAP_MATCH_TRADE_COMPLETION_RECONCILER_POLL_INTERVAL_MS:-1000}" \
    EAP_MATCH_RESERVATION_RECONCILER_ENABLED="${EAP_MATCH_RESERVATION_RECONCILER_ENABLED:-false}" \
    EAP_MATCH_RESERVATION_RECONCILER_BATCH_SIZE="${EAP_MATCH_RESERVATION_RECONCILER_BATCH_SIZE:-500}" \
    EAP_MATCH_RESERVATION_RECONCILER_POLL_INTERVAL_MS="${EAP_MATCH_RESERVATION_RECONCILER_POLL_INTERVAL_MS:-1000}" \
    EAP_MATCH_RESERVATION_CLEANUP_BATCH_SIZE="${EAP_MATCH_RESERVATION_CLEANUP_BATCH_SIZE:-1000}" \
    EAP_MATCH_RESERVATION_CLEANUP_POLL_INTERVAL_MS="${EAP_MATCH_RESERVATION_CLEANUP_POLL_INTERVAL_MS:-25}" \
    EAP_MATCH_RESERVATION_CLEANUP_INITIAL_BACKOFF_MS="${EAP_MATCH_RESERVATION_CLEANUP_INITIAL_BACKOFF_MS:-100}" \
    EAP_MATCH_RESERVATION_CLEANUP_MAX_BACKOFF_MS="${EAP_MATCH_RESERVATION_CLEANUP_MAX_BACKOFF_MS:-30000}" \
    EAP_MATCH_RESERVATION_CLEANUP_PROCESSING_TIMEOUT_SECONDS="${EAP_MATCH_RESERVATION_CLEANUP_PROCESSING_TIMEOUT_SECONDS:-10}" \
    EAP_MATCH_RESERVATION_CLEANUP_LEASE_CHUNK_SIZE="${EAP_MATCH_RESERVATION_CLEANUP_LEASE_CHUNK_SIZE:-50}" \
    EAP_ORDER_COMMAND_POOL_SIZE="${EAP_ORDER_COMMAND_POOL_SIZE:-35}" \
    EAP_ORDER_COMMAND_POOL_MIN_IDLE="${EAP_ORDER_COMMAND_POOL_MIN_IDLE:-35}" \
    EAP_ORDER_CONSUMER_POOL_SIZE="${EAP_ORDER_CONSUMER_POOL_SIZE:-20}" \
    EAP_ORDER_CONSUMER_POOL_MIN_IDLE="${EAP_ORDER_CONSUMER_POOL_MIN_IDLE:-5}" \
    EAP_ORDER_PROJECTION_POOL_SIZE="${EAP_ORDER_PROJECTION_POOL_SIZE:-3}" \
    EAP_ORDER_PROJECTION_POOL_MIN_IDLE="${EAP_ORDER_PROJECTION_POOL_MIN_IDLE:-1}" \
    EAP_ORDER_REALTIME_UPDATES_ENABLED="${EAP_ORDER_REALTIME_UPDATES_ENABLED:-false}" \
    EAP_ORDER_SUBMISSION_WRITE_MODE="${EAP_ORDER_SUBMISSION_WRITE_MODE:-current_order_path}" \
    EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_ENABLED="${EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_ENABLED:-false}" \
    EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_ENABLED="${EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_ENABLED:-false}" \
    EAP_ORDER_OUTBOX_BATCH_SIZE="${EAP_ORDER_OUTBOX_BATCH_SIZE:-500}" \
    EAP_ORDER_OUTBOX_PUBLISH_CONCURRENCY="${EAP_ORDER_OUTBOX_PUBLISH_CONCURRENCY:-1}" \
    EAP_ORDER_OUTBOX_BATCH_CONFIRM_ENABLED="${EAP_ORDER_OUTBOX_BATCH_CONFIRM_ENABLED:-true}" \
    EAP_ORDER_OUTBOX_ASYNC_RELAY_ENABLED="${EAP_ORDER_OUTBOX_ASYNC_RELAY_ENABLED:-false}" \
    EAP_RATE_LIMIT_ENABLED="${EAP_RATE_LIMIT_ENABLED:-true}" \
    EAP_RATE_LIMIT_BACKEND="${EAP_RATE_LIMIT_BACKEND:-local}" \
    EAP_ORDER_MARKET_SEQUENCE_ALLOCATION_BLOCK_SIZE="${EAP_ORDER_MARKET_SEQUENCE_ALLOCATION_BLOCK_SIZE:-1}" \
    EAP_ORDER_ASSET_RESERVATION_CONFIRMED_CONCURRENCY="${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_CONCURRENCY:-16}" \
    EAP_ORDER_ASSET_RESERVATION_CONFIRMED_BATCH_SIZE="${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_BATCH_SIZE:-50}" \
    EAP_ORDER_ASSET_RESERVATION_CONFIRMED_RECEIVE_TIMEOUT_MS="${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_RECEIVE_TIMEOUT_MS:-25}" \
    EAP_ORDER_ASSET_RESERVATION_CONFIRMED_SINGLE_ROUND_TRIP_ENABLED="${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_SINGLE_ROUND_TRIP_ENABLED:-true}" \
    EAP_ORDER_ASSET_RESERVATION_FAILED_CONCURRENCY="${EAP_ORDER_ASSET_RESERVATION_FAILED_CONCURRENCY:-4}" \
    EAP_ORDER_MATCHED_CONCURRENCY="${EAP_ORDER_MATCHED_CONCURRENCY:-16}" \
    EAP_ORDER_TRADE_EXECUTED_CONCURRENCY="${EAP_ORDER_TRADE_EXECUTED_CONCURRENCY:-12}" \
    EAP_ORDER_TRADE_EXECUTED_BATCH_SIZE="${EAP_ORDER_TRADE_EXECUTED_BATCH_SIZE:-50}" \
    EAP_ORDER_TRADE_EXECUTED_RECEIVE_TIMEOUT_MS="${EAP_ORDER_TRADE_EXECUTED_RECEIVE_TIMEOUT_MS:-25}" \
    EAP_ORDER_OUTBOX_POLL_INTERVAL_MS="${EAP_ORDER_OUTBOX_POLL_INTERVAL_MS:-100}" \
    EAP_ORDER_PROJECTION_POLL_INTERVAL_MS="${EAP_ORDER_PROJECTION_POLL_INTERVAL_MS:-5000}" \
    EAP_ORDER_PROJECTION_REPAIR_ENABLED="${EAP_ORDER_PROJECTION_REPAIR_ENABLED:-false}" \
    EAP_WALLET_DB_POOL_SIZE="${EAP_WALLET_DB_POOL_SIZE:-40}" \
    EAP_WALLET_DB_POOL_MIN_IDLE="${EAP_WALLET_DB_POOL_MIN_IDLE:-12}" \
    EAP_WALLET_RABBIT_CONCURRENCY="${EAP_WALLET_RABBIT_CONCURRENCY:-4}" \
    EAP_WALLET_RABBIT_MAX_CONCURRENCY="${EAP_WALLET_RABBIT_MAX_CONCURRENCY:-32}" \
    EAP_WALLET_RABBIT_PREFETCH="${EAP_WALLET_RABBIT_PREFETCH:-20}" \
    EAP_WALLET_ORDER_SUBMITTED_CONCURRENCY="${EAP_WALLET_ORDER_SUBMITTED_CONCURRENCY:-32}" \
    EAP_WALLET_OUTBOX_BATCH_SIZE="${EAP_WALLET_OUTBOX_BATCH_SIZE:-500}" \
    EAP_WALLET_OUTBOX_PUBLISH_CONCURRENCY="${EAP_WALLET_OUTBOX_PUBLISH_CONCURRENCY:-1}" \
    EAP_WALLET_TRADE_EXECUTED_CONCURRENCY="${EAP_WALLET_TRADE_EXECUTED_CONCURRENCY:-8}" \
    EAP_WALLET_OUTBOX_BATCH_CONFIRM_ENABLED="${EAP_WALLET_OUTBOX_BATCH_CONFIRM_ENABLED:-false}" \
    EAP_WALLET_OUTBOX_ASYNC_RELAY_ENABLED="${EAP_WALLET_OUTBOX_ASYNC_RELAY_ENABLED:-false}" \
    EAP_WALLET_OUTBOX_POLL_INTERVAL_MS="${EAP_WALLET_OUTBOX_POLL_INTERVAL_MS:-100}" \
    LOADTEST_SERVICE_LAUNCH_MODE="${LOADTEST_SERVICE_LAUNCH_MODE}" \
    LOADTEST_SERVICE_JAVA_BIN="${LOADTEST_SERVICE_JAVA_BIN}" \
    bash "${ROOT_DIR}/scripts/load-test/start-loadtest-services.sh"
}

http_matched_pre_reset_data() {
  if [[ "${PRE_RESET_DATA_BEFORE_SERVICE_START:-true}" != "true" ]]; then
    return 0
  fi
  echo "[INFO] resetting matched HTTP data before consumer startup"
  http_matched_export_generator_environment
  local reset_args="--market-id ${MARKET_ID} \
--order-jdbc-url ${ORDER_JDBC_URL} \
--wallet-jdbc-url ${WALLET_JDBC_URL} \
--match-jdbc-url ${MATCH_JDBC_URL} \
--jdbc-user ${JDBC_USER} \
--redis-host ${REDIS_HOST} \
--redis-port ${REDIS_PORT} \
--rabbit-management-url ${RABBIT_MANAGEMENT_URL} \
--rabbit-vhost ${RABBIT_VHOST} \
--rabbit-user ${RABBIT_USER} \
--flush-redis-on-reset ${FLUSH_REDIS_ON_RESET}"
  (
    cd "${ROOT_DIR}/eap-order"
    GRADLE_USER_HOME="${GRADLE_USER_HOME_DIR}" ./gradlew --no-daemon httpMatchedResetLoadTest \
      --args="${reset_args}"
  )
}

http_matched_stop_services() {
  if [[ "${STOP_SERVICES_AFTER_RUN}" == "true" ]]; then
    bash "${ROOT_DIR}/scripts/load-test/stop-loadtest-services.sh" >/dev/null 2>&1 || true
  fi
}

http_matched_cleanup() {
  http_matched_stop_diagnostics
  http_matched_stop_services
}

http_matched_export_generator_environment() {
  export EAP_LOADTEST_JDBC_PASSWORD="${JDBC_PASSWORD}"
  export EAP_LOADTEST_RABBIT_PASSWORD="${RABBIT_PASSWORD}"
  export EAP_LOADTEST_RABBIT_VHOST="${RABBIT_VHOST}"
}
