#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
LOG_DIR="${TMPDIR:-/tmp}/eap-loadtest-logs"
GRADLE_USER_HOME_DIR="${ROOT_DIR}/.cache/gradle"
SERVICE_LAUNCH_MODE="${LOADTEST_SERVICE_LAUNCH_MODE:-boot-run}"
SERVICE_JAVA_BIN="${LOADTEST_SERVICE_JAVA_BIN:-java}"
SERVICE_JAVA_VERSION="managed by Gradle toolchain"
SERVICE_JAVA_BIN_QUOTED=""

mkdir -p "$LOG_DIR" "$GRADLE_USER_HOME_DIR"

find_service_jar() {
  local repo="$1"

  find "${ROOT_DIR}/${repo}/build/libs" -maxdepth 1 -type f \
    -name "${repo}-*.jar" \
    ! -name "*-plain.jar" \
    ! -name "*-stubs.jar" \
    | sort \
    | head -n 1
}

case "${SERVICE_LAUNCH_MODE}" in
  boot-run)
    ;;
  jar)
    if [[ "${SERVICE_JAVA_BIN}" == */* ]]; then
      if [[ ! -x "${SERVICE_JAVA_BIN}" ]]; then
        echo "[ERROR] LOADTEST_SERVICE_JAVA_BIN is not executable: ${SERVICE_JAVA_BIN}" >&2
        exit 2
      fi
    elif ! command -v "${SERVICE_JAVA_BIN}" >/dev/null 2>&1; then
      echo "[ERROR] LOADTEST_SERVICE_JAVA_BIN was not found: ${SERVICE_JAVA_BIN}" >&2
      exit 2
    fi
    SERVICE_JAVA_VERSION="$("${SERVICE_JAVA_BIN}" -version 2>&1 | head -n 1)"
    printf -v SERVICE_JAVA_BIN_QUOTED '%q' "${SERVICE_JAVA_BIN}"
    for repo in eap-wallet eap-order eap-matchEngine; do
      echo "[INFO] preparing ${repo} executable jar"
      (
        cd "${ROOT_DIR}/${repo}"
        GRADLE_USER_HOME="${GRADLE_USER_HOME_DIR}" ./gradlew --no-daemon bootJar
      )
      if [[ -z "$(find_service_jar "${repo}")" ]]; then
        echo "[ERROR] executable jar was not produced for ${repo}" >&2
        exit 1
      fi
    done
    ;;
  *)
    echo "[ERROR] unsupported LOADTEST_SERVICE_LAUNCH_MODE=${SERVICE_LAUNCH_MODE}; expected boot-run or jar" >&2
    exit 2
    ;;
esac

start_service() {
  local repo="$1"
  local port="$2"
  local health_path="$3"
  local log_file="${LOG_DIR}/${repo}.log"
  local pid_file="${LOG_DIR}/${repo}.pid"
  local service_env=""
  local launch_command=""
  local redis_env="EAP_REDIS_SHARE_NATIVE_CONNECTION='${EAP_REDIS_SHARE_NATIVE_CONNECTION:-true}' SPRING_DATA_REDIS_LETTUCE_POOL_ENABLED='${EAP_REDIS_LETTUCE_POOL_ENABLED:-false}' SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE='${EAP_REDIS_LETTUCE_POOL_MAX_ACTIVE:-64}' SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE='${EAP_REDIS_LETTUCE_POOL_MAX_IDLE:-64}' SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE='${EAP_REDIS_LETTUCE_POOL_MIN_IDLE:-16}' SPRING_DATA_REDIS_LETTUCE_POOL_MAX_WAIT='${EAP_REDIS_LETTUCE_POOL_MAX_WAIT:-500ms}'"

  if [[ "${repo}" == "eap-matchEngine" ]]; then
    service_env="${redis_env} EAP_MATCH_DB_POOL_SIZE='${EAP_MATCH_DB_POOL_SIZE:-35}' EAP_MATCH_DB_POOL_MIN_IDLE='${EAP_MATCH_DB_POOL_MIN_IDLE:-10}' EAP_MATCH_RABBIT_CONCURRENCY='${EAP_MATCH_RABBIT_CONCURRENCY:-8}' EAP_MATCH_RABBIT_MAX_CONCURRENCY='${EAP_MATCH_RABBIT_MAX_CONCURRENCY:-32}' EAP_MATCH_RABBIT_PREFETCH='${EAP_MATCH_RABBIT_PREFETCH:-50}' EAP_MATCH_USER_OPEN_ORDER_INDEX_ENABLED='${EAP_MATCH_USER_OPEN_ORDER_INDEX_ENABLED:-true}' EAP_MATCH_ORDER_CONFIRMED_CONCURRENCY='${EAP_MATCH_ORDER_CONFIRMED_CONCURRENCY:-12}' EAP_MATCH_ORDER_TRADE_APPLIED_CONCURRENCY='${EAP_MATCH_ORDER_TRADE_APPLIED_CONCURRENCY:-12}' EAP_MATCH_WALLET_TRADE_SETTLED_CONCURRENCY='${EAP_MATCH_WALLET_TRADE_SETTLED_CONCURRENCY:-6}' EAP_MATCH_COMPLETION_MARKER_BATCH_SIZE='${EAP_MATCH_COMPLETION_MARKER_BATCH_SIZE:-50}' EAP_MATCH_COMPLETION_MARKER_RECEIVE_TIMEOUT_MS='${EAP_MATCH_COMPLETION_MARKER_RECEIVE_TIMEOUT_MS:-25}' EAP_MATCH_TRADE_OUTBOX_BATCH_SIZE='${EAP_MATCH_TRADE_OUTBOX_BATCH_SIZE:-500}' EAP_MATCH_TRADE_OUTBOX_PUBLISH_CONCURRENCY='${EAP_MATCH_TRADE_OUTBOX_PUBLISH_CONCURRENCY:-4}' EAP_MATCH_TRADE_OUTBOX_BATCH_CONFIRM_ENABLED='${EAP_MATCH_TRADE_OUTBOX_BATCH_CONFIRM_ENABLED:-false}' EAP_MATCH_TRADE_OUTBOX_POLL_INTERVAL_MS='${EAP_MATCH_TRADE_OUTBOX_POLL_INTERVAL_MS:-100}' EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED='${EAP_MATCH_TRADE_COMPLETION_HOT_PATH_ENABLED:-false}' EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED='${EAP_MATCH_TRADE_COMPLETION_RECONCILER_ENABLED:-false}' EAP_MATCH_TRADE_COMPLETION_RECONCILER_BATCH_SIZE='${EAP_MATCH_TRADE_COMPLETION_RECONCILER_BATCH_SIZE:-500}' EAP_MATCH_TRADE_COMPLETION_RECONCILER_POLL_INTERVAL_MS='${EAP_MATCH_TRADE_COMPLETION_RECONCILER_POLL_INTERVAL_MS:-1000}' EAP_MATCH_RESERVATION_RECONCILER_ENABLED='${EAP_MATCH_RESERVATION_RECONCILER_ENABLED:-false}' EAP_MATCH_RESERVATION_RECONCILER_BATCH_SIZE='${EAP_MATCH_RESERVATION_RECONCILER_BATCH_SIZE:-500}' EAP_MATCH_RESERVATION_RECONCILER_POLL_INTERVAL_MS='${EAP_MATCH_RESERVATION_RECONCILER_POLL_INTERVAL_MS:-1000}' EAP_MATCH_RESERVATION_CLEANUP_BATCH_SIZE='${EAP_MATCH_RESERVATION_CLEANUP_BATCH_SIZE:-1000}' EAP_MATCH_RESERVATION_CLEANUP_LEASE_CHUNK_SIZE='${EAP_MATCH_RESERVATION_CLEANUP_LEASE_CHUNK_SIZE:-50}' EAP_MATCH_RESERVATION_CLEANUP_POLL_INTERVAL_MS='${EAP_MATCH_RESERVATION_CLEANUP_POLL_INTERVAL_MS:-25}' EAP_MATCH_RESERVATION_CLEANUP_INITIAL_BACKOFF_MS='${EAP_MATCH_RESERVATION_CLEANUP_INITIAL_BACKOFF_MS:-100}' EAP_MATCH_RESERVATION_CLEANUP_MAX_BACKOFF_MS='${EAP_MATCH_RESERVATION_CLEANUP_MAX_BACKOFF_MS:-30000}' EAP_MATCH_RESERVATION_CLEANUP_PROCESSING_TIMEOUT_SECONDS='${EAP_MATCH_RESERVATION_CLEANUP_PROCESSING_TIMEOUT_SECONDS:-10}'"
  fi
  if [[ "${repo}" == "eap-wallet" ]]; then
    service_env="EAP_WALLET_DB_POOL_SIZE='${EAP_WALLET_DB_POOL_SIZE:-40}' EAP_WALLET_DB_POOL_MIN_IDLE='${EAP_WALLET_DB_POOL_MIN_IDLE:-12}' EAP_WALLET_RABBIT_CONCURRENCY='${EAP_WALLET_RABBIT_CONCURRENCY:-4}' EAP_WALLET_RABBIT_MAX_CONCURRENCY='${EAP_WALLET_RABBIT_MAX_CONCURRENCY:-32}' EAP_WALLET_RABBIT_PREFETCH='${EAP_WALLET_RABBIT_PREFETCH:-20}' EAP_WALLET_ORDER_SUBMITTED_CONCURRENCY='${EAP_WALLET_ORDER_SUBMITTED_CONCURRENCY:-32}' EAP_WALLET_TRADE_EXECUTED_CONCURRENCY='${EAP_WALLET_TRADE_EXECUTED_CONCURRENCY:-12}' EAP_WALLET_OUTBOX_BATCH_SIZE='${EAP_WALLET_OUTBOX_BATCH_SIZE:-500}' EAP_WALLET_OUTBOX_PUBLISH_CONCURRENCY='${EAP_WALLET_OUTBOX_PUBLISH_CONCURRENCY:-1}' EAP_WALLET_OUTBOX_BATCH_CONFIRM_ENABLED='${EAP_WALLET_OUTBOX_BATCH_CONFIRM_ENABLED:-false}' EAP_WALLET_OUTBOX_ASYNC_RELAY_ENABLED='${EAP_WALLET_OUTBOX_ASYNC_RELAY_ENABLED:-false}' EAP_WALLET_OUTBOX_ASYNC_MAX_IN_FLIGHT_BATCHES='${EAP_WALLET_OUTBOX_ASYNC_MAX_IN_FLIGHT_BATCHES:-4}' EAP_WALLET_OUTBOX_IN_FLIGHT_TIMEOUT_SECONDS='${EAP_WALLET_OUTBOX_IN_FLIGHT_TIMEOUT_SECONDS:-30}' EAP_WALLET_OUTBOX_POLL_INTERVAL_MS='${EAP_WALLET_OUTBOX_POLL_INTERVAL_MS:-100}'"
  fi
  if [[ "${repo}" == "eap-order" ]]; then
    local order_command_pool_size="${EAP_ORDER_COMMAND_POOL_SIZE:-35}"
    service_env="${redis_env} EAP_ORDER_COMMAND_POOL_SIZE='${order_command_pool_size}' EAP_ORDER_COMMAND_POOL_MIN_IDLE='${EAP_ORDER_COMMAND_POOL_MIN_IDLE:-${order_command_pool_size}}' EAP_ORDER_CONSUMER_POOL_SIZE='${EAP_ORDER_CONSUMER_POOL_SIZE:-20}' EAP_ORDER_CONSUMER_POOL_MIN_IDLE='${EAP_ORDER_CONSUMER_POOL_MIN_IDLE:-5}' EAP_ORDER_PROJECTION_POOL_SIZE='${EAP_ORDER_PROJECTION_POOL_SIZE:-3}' EAP_ORDER_PROJECTION_POOL_MIN_IDLE='${EAP_ORDER_PROJECTION_POOL_MIN_IDLE:-1}' EAP_ORDER_REALTIME_UPDATES_ENABLED='${EAP_ORDER_REALTIME_UPDATES_ENABLED:-false}' EAP_ORDER_SUBMISSION_WRITE_MODE='${EAP_ORDER_SUBMISSION_WRITE_MODE:-current_order_path}' EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_ENABLED='${EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_ENABLED:-false}' EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_BATCH_SIZE='${EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_BATCH_SIZE:-500}' EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_MAX_BATCHES_PER_TICK='${EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_MAX_BATCHES_PER_TICK:-4}' EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_POLL_INTERVAL_MS='${EAP_ORDER_SUBMISSION_HEAD_PROJECTOR_POLL_INTERVAL_MS:-25}' EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_ENABLED='${EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_ENABLED:-false}' EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_BATCH_SIZE='${EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_BATCH_SIZE:-500}' EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_POLL_INTERVAL_MS='${EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_POLL_INTERVAL_MS:-25}' EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_CONFIRM_TIMEOUT_MS='${EAP_ORDER_SUBMISSION_EVENT_STORE_RELAY_CONFIRM_TIMEOUT_MS:-5000}' EAP_ORDER_OUTBOX_BATCH_SIZE='${EAP_ORDER_OUTBOX_BATCH_SIZE:-500}' EAP_ORDER_OUTBOX_PUBLISH_CONCURRENCY='${EAP_ORDER_OUTBOX_PUBLISH_CONCURRENCY:-1}' EAP_ORDER_OUTBOX_BATCH_CONFIRM_ENABLED='${EAP_ORDER_OUTBOX_BATCH_CONFIRM_ENABLED:-true}' EAP_ORDER_OUTBOX_ASYNC_RELAY_ENABLED='${EAP_ORDER_OUTBOX_ASYNC_RELAY_ENABLED:-false}' EAP_ORDER_OUTBOX_IN_FLIGHT_TIMEOUT_SECONDS='${EAP_ORDER_OUTBOX_IN_FLIGHT_TIMEOUT_SECONDS:-30}' EAP_ORDER_OUTBOX_POLL_INTERVAL_MS='${EAP_ORDER_OUTBOX_POLL_INTERVAL_MS:-100}' EAP_ORDER_PROJECTION_POLL_INTERVAL_MS='${EAP_ORDER_PROJECTION_POLL_INTERVAL_MS:-5000}' EAP_ORDER_PROJECTION_REPAIR_ENABLED='${EAP_ORDER_PROJECTION_REPAIR_ENABLED:-false}' EAP_RATE_LIMIT_ENABLED='${EAP_RATE_LIMIT_ENABLED:-true}' EAP_RATE_LIMIT_BACKEND='${EAP_RATE_LIMIT_BACKEND:-local}' EAP_ORDER_MARKET_SEQUENCE_ALLOCATION_BLOCK_SIZE='${EAP_ORDER_MARKET_SEQUENCE_ALLOCATION_BLOCK_SIZE:-1}' EAP_ORDER_ASSET_RESERVATION_CONFIRMED_CONCURRENCY='${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_CONCURRENCY:-16}' EAP_ORDER_ASSET_RESERVATION_CONFIRMED_BATCH_SIZE='${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_BATCH_SIZE:-50}' EAP_ORDER_ASSET_RESERVATION_CONFIRMED_RECEIVE_TIMEOUT_MS='${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_RECEIVE_TIMEOUT_MS:-25}' EAP_ORDER_ASSET_RESERVATION_CONFIRMED_SINGLE_ROUND_TRIP_ENABLED='${EAP_ORDER_ASSET_RESERVATION_CONFIRMED_SINGLE_ROUND_TRIP_ENABLED:-true}' EAP_ORDER_ASSET_RESERVATION_FAILED_CONCURRENCY='${EAP_ORDER_ASSET_RESERVATION_FAILED_CONCURRENCY:-4}' EAP_ORDER_MATCHED_CONCURRENCY='${EAP_ORDER_MATCHED_CONCURRENCY:-16}' EAP_ORDER_TRADE_EXECUTED_CONCURRENCY='${EAP_ORDER_TRADE_EXECUTED_CONCURRENCY:-12}' EAP_ORDER_TRADE_EXECUTED_BATCH_SIZE='${EAP_ORDER_TRADE_EXECUTED_BATCH_SIZE:-50}' EAP_ORDER_TRADE_EXECUTED_RECEIVE_TIMEOUT_MS='${EAP_ORDER_TRADE_EXECUTED_RECEIVE_TIMEOUT_MS:-25}'"
  fi

  if lsof -Pi ":${port}" -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "[WARN] port ${port} is already in use; stop the existing process before starting ${repo}" >&2
    return 1
  fi

  case "${SERVICE_LAUNCH_MODE}" in
    boot-run)
      launch_command="GRADLE_USER_HOME='${GRADLE_USER_HOME_DIR}' ./gradlew --no-daemon bootRun --args='--spring.profiles.active=loadtest'"
      ;;
    jar)
      local boot_jar
      boot_jar="$(find_service_jar "${repo}")"
      launch_command="exec ${SERVICE_JAVA_BIN_QUOTED} -jar '${boot_jar}' --spring.profiles.active=loadtest"
      ;;
  esac

  echo "[INFO] starting ${repo} on port ${port}; launchMode=${SERVICE_LAUNCH_MODE}; log=${log_file}"
  nohup bash -lc "cd '${ROOT_DIR}/${repo}' && ${service_env} ${launch_command}" >"${log_file}" 2>&1 &
  echo "$!" >"${pid_file}"

  local health_url="http://localhost:${port}${health_path}"
  local deadline=$(( $(date +%s) + ${LOADTEST_SERVICE_START_TIMEOUT_SECONDS:-120} ))
  until curl -fsS "${health_url}" >/dev/null 2>&1; do
    if [[ $(date +%s) -ge $deadline ]]; then
      echo "[ERROR] ${repo} did not become ready: ${health_url}" >&2
      tail -n 80 "${log_file}" >&2 || true
      return 1
    fi
    if ! kill -0 "$(cat "${pid_file}")" >/dev/null 2>&1; then
      echo "[ERROR] ${repo} exited before becoming ready: ${health_url}" >&2
      tail -n 80 "${log_file}" >&2 || true
      return 1
    fi
    sleep 1
  done
  echo "[INFO] ${repo} ready"
}

start_service eap-wallet 8081 /eap-wallet/actuator/health
start_service eap-order 8080 /eap-order/actuator/health
start_service eap-matchEngine 8082 /match-engine/actuator/health

echo "[INFO] loadtest services ready"
echo "[INFO] service launch mode: ${SERVICE_LAUNCH_MODE}"
echo "[INFO] service Java: ${SERVICE_JAVA_VERSION}; binary=${SERVICE_JAVA_BIN}"
echo "[INFO] logs:"
echo "  tail -f ${LOG_DIR}/eap-wallet.log"
echo "  tail -f ${LOG_DIR}/eap-order.log"
echo "  tail -f ${LOG_DIR}/eap-matchEngine.log"
